/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/Bobs.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { useGlobalContext } from '../../app/Context/status'
import * as THREE from 'three'
const Model = (props) => {
  const { door } = useGlobalContext()
  const { color } = useGlobalContext()
  const { IM } = useGlobalContext()
  const newColor = new THREE.Color('#EEE9E7')
  const data = [
    { color: '#EEE9E7', colorName: 'Wevet' },
    { color: '#C4BEB4', colorName: 'Purbeck stone' },
    { color: '#DFD6CB', colorName: 'Skimming Stone' },
    { color: '#C0C2B3', colorName: 'Mizzle' },
  ]
  const { nodes, materials } = useGLTF('/model/Bobs.gltf')
  return (
    <group {...props} dispose={null}>
      {/* <group position={[0, 0.58, 0.53]} rotation={[-0.04, 0.61, 0]}>
        <mesh
          geometry={nodes.Door.geometry}
          material={materials['Wood-4']}
          position={[0.69, 0.75, -0.14]}
        />
        <mesh
          geometry={nodes.Door001.geometry}
          material={materials['Painted wooden door']}
          position={[0.69, 0.75, -0.13]}
        />
        <mesh
          geometry={nodes.Door002.geometry}
          material={materials['Painted wooden door']}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door003.geometry}
          material={materials['Painted wooden door']}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door004.geometry}
          material={materials['Painted wooden door']}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door005.geometry}
          material={materials['Painted wooden door']}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        /> */}
      {/* </group> */}
      <group position={[-0.41, 1.07, 0.09]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Cube032_1.geometry}
          material={materials.BrushedSteel}
        />
        <mesh
          geometry={nodes.Cube032_2.geometry}
          material={materials['Wood-5']}
          material-color={color}
        />
      </group>
      <mesh
        geometry={nodes['Interior_Door_and_Frame_#11002'].geometry}
        material={materials.Chrome}
        position={[-1.1, 1.07, 0]}
        material-color={color}
      />
      <mesh
        geometry={nodes['Interior_Door_and_Frame_#11003'].geometry}
        material={materials.Chrome}
        position={[-0.9, 1.12, 0.82]}
        rotation={[-0.05, 0.47, 0.02]}
        scale={[1.01, 1.03, 0.98]}
      />
    </group>
  )
}

useGLTF.preload('/Bobs.gltf')
export default Model
