/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/Door2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Door2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-7.45, -1.3, 5.23]} scale={0.05}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.DK_Metal} position={[160.63, 49.1, -104.08]} rotation={[0.54, 0.05, -1.57]} scale={21.53} />
      </group>
      <mesh geometry={nodes.Door.geometry} material={materials.WhiteWood} position={[0.01, 0, -0.49]}>
        <mesh geometry={nodes.handle.geometry} material={materials.MetalBronzeChrome} position={[-0.03, 0.98, 0.84]} />
        <mesh geometry={nodes.Lock1.geometry} material={materials.MetalBronzeChrome} position={[0.01, 0.87, 0.88]} />
        <mesh geometry={nodes.Lock1001.geometry} material={materials.MetalBronzeChrome} position={[-0.06, 0.87, 0.88]} rotation={[Math.PI, 0, Math.PI]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Door2.gltf')
