/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/Door+nobs.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGlobalContext } from '../../app/Context/status'
import * as THREE from 'three'
const Door = (props) => {
  const { nodes, materials } = useGLTF('./model/Door+nobs.gltf')
  const { door } = useGlobalContext()
  const { color } = useGlobalContext()
  const { IM } = useGlobalContext()
  const newColor = new THREE.Color('##EEE9E7')
  const data = [
    { color: '#EEE9E7', colorName: 'Wevet' },
    { color: '#C4BEB4', colorName: 'Purbeck stone' },
    { color: '#DFD6CB', colorName: 'Skimming Stone' },
    { color: '#C0C2B3', colorName: 'Mizzle' },
  ]
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.58, 0.53]} rotation={[-0.04, 0.61, 0]}>
        <mesh
          geometry={nodes.Door.geometry}
          material={materials['Painted wooden door']}
          material-color={color}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door001.geometry}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
          visible={IM === 'Doorknob' ? true : false}
        />
        {/* <mesh
          geometry={nodes.Door002.geometry}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door003.geometry}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door004.geometry}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        />
        <mesh
          geometry={nodes.Door005.geometry}
          position={[0.69, 0.72, -0.14]}
          rotation={[0, -0.61, 0.02]}
        /> */}
      </group>
      {/* <group position={[-0.41, 1.07, 0.09]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Cube032_1.geometry}
          material={materials.BrushedSteel}
        />
        <mesh
          geometry={nodes.Cube032_2.geometry}
          material={materials['Wood-5']}
        />
      </group> */}
      <mesh
        geometry={nodes['Interior_Door_and_Frame_#11002'].geometry}
        material={materials.Chrome}
        position={[-1.1, 1.07, 0]}
        visible={IM === 'Doorhandle' ? true : false}
      />
      <mesh
        geometry={nodes['Interior_Door_and_Frame_#11003'].geometry}
        position={[-1.1, 1.07, -0.05]}
        rotation={[0, -0.05, 0]}
        visible={IM === 'Doorhandle' ? true : false}
      />
    </group>
  )
}

useGLTF.preload('/Door+nobs.gltf')

export default Door

// Wevet #EEE9E7
// Purbeck Stone #C4BEB4
// DFD6CB Skimming stone
// Mizzle C0C2B3
